import 'package:flutter/cupertino.dart';
import 'package:hexcolor/hexcolor.dart';
import 'package:moblie_ui/image_path.dart';
import 'package:moblie_ui/models/mobileCatergoryModel.dart';
//import 'package:flutter_screenutil/flutter_screenutil.dart';

class ListWidgets {
  static List<MobileProductModel> mobileList = <MobileProductModel>[
    MobileProductModel(
      containerMargin: EdgeInsets.fromLTRB(5, 5, 5, 5),
      containerPadding: EdgeInsets.fromLTRB(5, 0, 5, 0),
      containerHeight: 250,
      containerWidth: 150,
      imageName: SamsungImg,
      imageHeight: 150,
      fit: BoxFit.fill,
      textName1: 'Samsung Galaxy',
      fontSize1: 12,
      fontWeight1: FontWeight.w600,
      textName2: 'Lite (Aura Black..',
      fontSize2: 12,
      fontWeight2: FontWeight.w600,
      textName3: 'Sold by Digital World Galaxy',
      fontSize3: 10,
      fontWeight3: FontWeight.w300,
      textName4: '\u{20B9}${60999}',
      fontSize4: 18,
      fontWeight4: FontWeight.bold,
      color4: HexColor('#129740'),
      textName5: '4.2',
    ),
    MobileProductModel(
      containerMargin: EdgeInsets.fromLTRB(5, 5, 5, 5),
      containerPadding: EdgeInsets.fromLTRB(5, 0, 5, 0),
      containerHeight: 250,
      containerWidth: 150,
      imageName: MobileProduct2,
      imageHeight: 150,
      fit: BoxFit.fill,
      textName1: 'Apple iPhone SE (Black,',
      fontSize1: 12,
      fontWeight1: FontWeight.w600,
      textName2: '64 GB',
      fontSize2: 12,
      fontWeight2: FontWeight.w600,
      textName3: 'Sold by Digital World Galaxy',
      fontSize3: 10,
      fontWeight3: FontWeight.w300,
      textName4: '\u{20B9}${34300}',
      fontSize4: 18,
      fontWeight4: FontWeight.bold,
      color4: HexColor('#129740'),
      textName5: '4.2',
    ),
    MobileProductModel(
      containerMargin: EdgeInsets.fromLTRB(5, 5, 5, 5),
      containerPadding: EdgeInsets.fromLTRB(5, 0, 5, 0),
      containerHeight: 250,
      containerWidth: 150,
      imageName: MobileImg,
      imageHeight: 150,
      fit: BoxFit.fill,
      textName1: 'Redmi Note 9 Pro',
      fontSize1: 12,
      fontWeight1: FontWeight.w600,
      textName2: 'Inserstellar Black, 64GB',
      fontSize2: 12,
      fontWeight2: FontWeight.w600,
      textName3: 'Sold by Digital World Galaxy',
      fontSize3: 10,
      fontWeight3: FontWeight.w300,
      textName4: '\u{20B9}${14999}',
      fontSize4: 18,
      fontWeight4: FontWeight.bold,
      color4: HexColor('#129740'),
      textName5: '4.2',
    ),
    MobileProductModel(
      containerMargin: EdgeInsets.fromLTRB(5, 5, 5, 5),
      containerPadding: EdgeInsets.fromLTRB(5, 0, 5, 0),
      containerHeight: 250,
      containerWidth: 150,
      imageName: MobileProduct7,
      imageHeight: 150,
      fit: BoxFit.fill,
      textName1: 'OnePlus 7 Pro (Mirror',
      fontSize1: 12,
      fontWeight1: FontWeight.w600,
      textName2: 'Grey, 128 GB (6 GB RAM)',
      fontSize2: 12,
      fontWeight2: FontWeight.w600,
      textName3: 'Sold by Digital World Galaxy',
      fontSize3: 10,
      fontWeight3: FontWeight.w300,
      textName4: '\u{20B9}${42999}',
      fontSize4: 18,
      fontWeight4: FontWeight.bold,
      color4: HexColor('#129740'),
      textName5: '4.2',
    ),
    MobileProductModel(
      containerMargin: EdgeInsets.fromLTRB(5, 5, 5, 5),
      containerPadding: EdgeInsets.fromLTRB(5, 0, 5, 0),
      containerHeight: 250,
      containerWidth: 150,
      imageName: MobileImg,
      imageHeight: 150,
      fit: BoxFit.fill,
      textName1: 'Realme 6 (Cornet Blue,',
      fontSize1: 12,
      fontWeight1: FontWeight.w600,
      textName2: '64 GB) (4 GB RAM)',
      fontSize2: 12,
      fontWeight2: FontWeight.w600,
      textName3: 'Sold by Digital World Galaxy',
      fontSize3: 10,
      fontWeight3: FontWeight.w300,
      textName4: '\u{20B9}${18149}',
      fontSize4: 18,
      fontWeight4: FontWeight.bold,
      color4: HexColor('#129740'),
      textName5: '4.2',
    ),
    MobileProductModel(
      containerMargin: EdgeInsets.fromLTRB(5, 5, 5, 5),
      containerPadding: EdgeInsets.fromLTRB(5, 0, 5, 0),
      containerHeight: 250,
      containerWidth: 150,
      imageName: MobileProduct6,
      imageHeight: 150,
      fit: BoxFit.fitHeight,
      textName1: 'OPPP Reno3 Pro',
      fontSize1: 12,
      fontWeight1: FontWeight.w600,
      textName2: ' (Sky White, 128 GB)',
      fontSize2: 12,
      fontWeight2: FontWeight.w600,
      textName3: 'Sold by Digital World Galaxy',
      fontSize3: 10,
      fontWeight3: FontWeight.w300,
      textName4: '\u{20B9}${43300}',
      fontSize4: 18,
      fontWeight4: FontWeight.bold,
      color4: HexColor('#129740'),
      textName5: '4.2',
    ),
  ];
}
