import 'package:flutter/material.dart';
import 'package:hexcolor/hexcolor.dart';
import 'package:moblie_ui/image_path.dart';
import 'package:moblie_ui/models/searchListItemModel.dart';

class SearchListItemWidget {
  static List<SearchItem> listItem = <SearchItem>[
    SearchItem(
      containerMargin: EdgeInsets.fromLTRB(5, 5, 5, 5),
      containerPadding: EdgeInsets.fromLTRB(5, 0, 5, 0),
      containerHeight: 250,
      containerWidth: 150,
      imageName: BosesImg,
      imageHeight: 150,
      fit: BoxFit.fill,
      textName1: 'Samsung Galaxy',
      fontSize1: 14,
      fontWeight1: FontWeight.w600,
      textName2: 'Lite (Aura Black..',
      fontSize2: 14,
      fontWeight2: FontWeight.w600,
      textName3: 'Sold by Digital World Galaxy',
      fontSize3: 10,
      fontWeight3: FontWeight.w300,
      textName4: '\u{20B9}${60999}',
      fontSize4: 18,
      fontWeight4: FontWeight.bold,
      color4: HexColor('#129740'),
      textName5: '4.2',
    ),
    SearchItem(
      containerMargin: EdgeInsets.fromLTRB(5, 5, 5, 5),
      containerPadding: EdgeInsets.fromLTRB(5, 0, 5, 0),
      containerHeight: 250,
      containerWidth: 150,
      imageName: BosesImg,
      imageHeight: 150,
      fit: BoxFit.fill,
      textName1: 'Samsung Galaxy',
      fontSize1: 14,
      fontWeight1: FontWeight.w600,
      textName2: 'Lite (Aura Black..',
      fontSize2: 14,
      fontWeight2: FontWeight.w600,
      textName3: 'Sold by Digital World Galaxy',
      fontSize3: 10,
      fontWeight3: FontWeight.w300,
      textName4: '\u{20B9}${60999}',
      fontSize4: 18,
      fontWeight4: FontWeight.bold,
      color4: HexColor('#129740'),
      textName5: '4.2',
    ),
    SearchItem(
      containerMargin: EdgeInsets.fromLTRB(5, 5, 5, 5),
      containerPadding: EdgeInsets.fromLTRB(5, 0, 5, 0),
      containerHeight: 250,
      containerWidth: 150,
      imageName: BosesImg,
      imageHeight: 150,
      fit: BoxFit.fill,
      textName1: 'Bose HeadPhones',
      fontSize1: 14,
      fontWeight1: FontWeight.w600,
      textName2: 'Lite (Aura Black..',
      fontSize2: 14,
      fontWeight2: FontWeight.w600,
      textName3: 'Sold by Digital World Galaxy',
      fontSize3: 10,
      fontWeight3: FontWeight.w300,
      textName4: '\u{20B9}${60999}',
      fontSize4: 18,
      fontWeight4: FontWeight.bold,
      color4: HexColor('#129740'),
      textName5: '4.2',
    ),
    SearchItem(
      containerMargin: EdgeInsets.fromLTRB(5, 5, 5, 5),
      containerPadding: EdgeInsets.fromLTRB(5, 0, 5, 0),
      containerHeight: 250,
      containerWidth: 150,
      imageName: SamsungImg,
      imageHeight: 150,
      fit: BoxFit.fill,
      textName1: 'Samsung Galaxy',
      fontSize1: 14,
      fontWeight1: FontWeight.w600,
      textName2: 'Lite (Aura Black..',
      fontSize2: 14,
      fontWeight2: FontWeight.w600,
      textName3: 'Sold by Digital World Galaxy',
      fontSize3: 10,
      fontWeight3: FontWeight.w300,
      textName4: '\u{20B9}${60999}',
      fontSize4: 18,
      fontWeight4: FontWeight.bold,
      color4: HexColor('#129740'),
      textName5: '4.2',
    ),
  ];
}
